### ISSUE TITLE
deprecate readtable & writetable for CSV.read & CSV.write

### ISSUE THREAD

**Issue by cjprybol** [JuliaData/DataTables.jl#10]
a find & replace of `DataFrame` -> `DataTable` project-wide for each was sufficient to get those working.
- [ ] DataStreams.jl
    - issue https://github.com/JuliaData/DataStreams.jl/issues/27
    - ready branch https://github.com/cjprybol/DataStreams.jl/tree/cjp/DataTables
- [ ] CSV.jl
    - ready branch https://github.com/cjprybol/CSV.jl/tree/cjp/DataTables

after those changes we'll deprecate
- [ ] `readtable` in favor of `CSV.read`
- [ ] `writetable` in favor of `CSV.write`

I've seen this discussed but couldn't find an open issue

**Comment by nalimilan** [comment]
Cc: @quinnj

**Comment by deyandyankov** [comment]
I just want to point out that `writetable` and `readtable` are still in the online docs but are not defined in the module (or module docs). Perhaps the online documentation needs to be rebuilt?

**Comment by nalimilan** [comment]
Indeed, there's [an error when building the manual](https://travis-ci.org/JuliaData/DataTables.jl/jobs/235951714#L324): `ERROR: LoadError: 'man/io.md' is not an existing page!`. That reference should be removed from the files.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/DataTables.jl/pull/71.

**Comment by cjprybol** [comment]
https://github.com/JuliaData/DataTables.jl/pull/26
