### ISSUE TITLE
How do I use CSV.read to return a DataTable instead of a DataFrame?

### ISSUE THREAD

**Issue by holder66** [JuliaData/DataTables.jl#47]
Unable to find this in the documentation.

**Comment by ararslan** [comment]
This issue should be opened on [CSV.jl](https://github.com/JuliaData/CSV.jl) instead.

**Comment by holder66** [comment]
Will do! Thanks.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/CSV.jl/pull/63.
