### ISSUE TITLE
Don't reexport Statsbase

### ISSUE THREAD

**Issue by mpastell** [JuliaData/DataTables.jl#58]
Would it be possible to not reexport Statsbase? I often use DataTables (and DataFrames) without using Statsbase.

I think the reexport is not intuitive and having `fit` and `predict` exported is annoying when using DataTables with ScikitLearn.jl . Also DataTables exporting things like `autocor` is a bit weird.

**Comment by ararslan** [comment]
Is the StatsBase dependency even still relevant for this package? It is for DataFrames since that still has the modeling functionality, but AFAICT there's nothing here that needs it. (I may well be missing something though.)

**Comment by cjprybol** [comment]
I think it's only needed for `StatsBase.describe`, the rest of the package doesn't need to be exported. But it seems that `using StatsBase`, adding methods with `StatsBase.describe = ...`, and exporting it by name via `export describe` works just fine. At least that's what the tests say in https://github.com/JuliaData/DataTables.jl/issues/59

**Comment by ararslan** [comment]
Ah yes, I had forgotten about `describe`. I guess we do still need it then.

**Comment by ararslan** [comment]
Fixed by #59.

**Comment by mpastell** [comment]
Thanks! That was fast!
