### ISSUE TITLE
Join on columns of different name

### ISSUE THREAD

**Issue by prcastro** [JuliaData/DataTables.jl#78]
The docs say we have to join only on columns that have the same name on both DTs. What about using
```julia
join(a, b, on=(:a_name, :b_name))
join(a, b, on=[(:a_name1, :b_name1), (:a_name2, :b_name2)])
```
for joining on columns of different names? This is because I think that is common to reuse a and b after the merge, so it's not nice to have the obligation to rename in case of a merge.

**Comment by davidanthoff** [comment]
I've also run into this issue, so +1 to this idea.

You could also use [Query.jl](https://github.com/davidanthoff/Query.jl) to do this right now, its various join commands allow you to join on columns with different names (or rather, it joins on whatever the expressions to the left and right of the ``equals`` keyword return, i.e. you can have arbitrary complicated transformations there as long as they are valid julia code). No promise about performance, though, I haven't spent much time on tuning the join commands (this mainly means I just don't know how they perform).

**Comment by nalimilan** [comment]
Makes sense, though we currently concentrate on stabilizing the basics, so without help it won't probably be implemented very soon.

**Comment by cjprybol** [comment]
transferred to DataFrames, see https://github.com/JuliaData/DataFrames.jl/issues/1297

**Comment by cjprybol** [comment]
@prcastro This functionality was just merged into DataFrames.jl with https://github.com/JuliaData/DataFrames.jl/pull/1312. It should work on master and will be present in the next release. Thanks for posting the issue!
